name: "Bug"
description: "报告 bug / File a bug report to help us improve"
labels: [bug]
body:
- type: checkboxes
  attributes:
    label: 模块 / Components
    description: |
      选择 bug 所在的模块。
      Please select the components you are filing a bug for
    options:
      - label: damocles-manager
        required: false
      - label: damocles-worker
        required: false
      - label: 工具链 / toolchains
        required: false
      - label: 文档 / docs
        required: false
- type: textarea
  id: version
  attributes:
    label: 版本 / Version
    render: text
    description: |
      填写 `./dist/damocles-manager --version` 和/或 `./dist/damocles-worker --version` 的输出内容。
      Enter the output of `./dist/damocles-manager --version` and/or `./dist/damocles-worker --version` if applicable.
    placeholder: |
      e.g.
      damocles-manager version v0.3.0-rc1-prod-git.f97994a
      damocles-worker v0.3.0-rc1-git.f97994a
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: 描述 / Describe the Bug
    description: |
      填写你所遇到的崩溃、异常信息或你认为与预期结果不符的行为。
      This is where you get to tell us what went wrong, when doing so, please try to provide a clear and concise description of the bug with all related information:
  validations:
    required: true
- type: textarea
  id: logging
  attributes:
    label: 日志 / Logging Information
    render: text
    description: |
      填写可以帮助定位问题的日志信息。
      Please provide debug logs of the problem.
      If you don't provide detailed logs when you raise the issue it will almost certainly be the first request I make before furthur diagnosing the problem.
  validations:
    required: true
- type: textarea
  id: reproduce
  attributes:
    label: 重现步骤 / Repo Steps
    description: |
      能够重现问题的步骤。
      Steps to reproduce the behavior.
    placeholder: |
      1. Run '...'
      2. Do '...'
      3. See error '...'
      ...
  validations:
    required: false
