# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

# Stable configurations
edition = "2021"
max_width = 140
merge_derives = true
use_field_init_shorthand = true
use_try_shorthand = true

# Nightly configurations
