name: vc-processors-publish

on:
  push:
    tags: ["vc-processors/v**"]

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: read rust toolchain
        id: read-rust-toolchain
        run: |
          echo "toolchain=$(cat ./rust-toolchain)" >> "$GITHUB_OUTPUT"

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ steps.read-rust-toolchain.outputs.toolchain }}

      - name: dependencies
        run: sudo apt update && sudo apt install --reinstall ocl-icd-opencl-dev libhwloc-dev -y

      - name: cargo-publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_CRATES_IO_API_TOKEN }}
        run: make -C ./damocles-worker/ publish-vc-processors
